global using Core.Models;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using Core.Data;
global using Core.Services;
global using Core.Services.Users;
global using Core.Services.Tickets;
global using Core.Services.Events;
global using System.Text.Json.Serialization;