global using Microsoft.AspNetCore.Mvc;
global using Core.Data;
global using Core.Models;
global using Core.Services;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Core.Services.Users;
global using Core.Services.Events;
global using Core.Services.Tickets;
global using FluentValidation;